backend:
  name: git-gateway
  branch: master

media_folder: assets/blog-img

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    format: "frontmatter"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "ID", name: "id", widget: "number" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "img", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Description", name: "postDesc", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
