backend:
  name: git-gateway
  branch: master

media_folder: assets/media-uploads
publish_mode: editorial_workflow
show_preview_links: true

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    format: "frontmatter"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - {
          label: "Exclusive content",
          name: "exclusive",
          widget: "boolean",
          default: false,
        }
      - { label: "Image", name: "img", widget: "string" }
      - { label: "Alt", name: "alt", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          date_format: "YYYY-MM-DD",
        }
      - { label: "Description", name: "postDesc", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "dev"
    label: "Dev"
    folder: "content/dev"
    format: "frontmatter"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Image", name: "img", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          date_format: "YYYY-MM-DD",
        }
      - { label: "Description", name: "postDesc", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "help"
    label: "Help"
    folder: "content/help"
    format: "frontmatter"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Description", name: "postDesc", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
